id: P353CF4A0
initial_creation_type: input
source_metadata:
  title: Long-Life Prayers
  language: es
  description: 'A selection of prayers for longevity (zhabs brtan), first more general
    ones, then those for specific individuals (arranged alphabetically by subject):'
  volume:
    88117dba02034c8d8ea7a840e594599f:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: General
    a0ae4eea7b2c4dca976d56028ad9e19f:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: General
    e7ea26128b2b4418875503abc5cde093:
      title: General Long-Life Prayer
      parent: General
    d5302940114b4f8d8aeae9000e8c8b20:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: General
    81cf27dce83a410b850a3c7768841f6c:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Alak Zenkar Rinpoche
    e4bed7fdc13d47e980047f9722745b01:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Alak Zenkar Rinpoche
    2b9b9c8234b24d47870e22793647d339:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Chökyi Nyima Rinpoche
    83ee330e2bc543e1b7a00a83fdaa735d:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      parent: Ḍākinī Muntso Rinpoche
    e13403743ebe4d3e903cf4f799b1e357:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Dezhung Rinpoche
    039493aeceee4ff9bf295ac08fa11c5b:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Dilgo Khyentse Yangsi Rinpoche
    511f5aeca2234725ba3d349e3afda527:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Dodrupchen Rinpoche
    5f807e66adfc42da83c6b4246fed076b:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Dudjom Rinpoche
    fbcce6a55f454c878367778802569115:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Dzogchen Rinpoche
    bfabc438d71d4e29b94afb3764690b7a:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Dzongsar Khyentse Rinpoche
    277cb17a1afd4332895b4fd09df41e30:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Dzongsar Khyentse Rinpoche
    ad86432c94d7400c925d8a218c1db4a5:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Dzongsar Khyentse Rinpoche
    76b1fc5181a14bafae0cc85c00e69a76:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    5f45e04c2c9f482eb04578321485f0df:
      title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His
        Holiness the Dalai Lama'
      parent: Fourteenth Dalai Lama
    5117d9ed499f4c63897bec65e1ccb48f:
      title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life
        of His Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One
        by Jamyang Khyentse Chökyi Lodrö'
      parent: Fourteenth Dalai Lama
    21e5520c1d854bdfad60195cb49c4ac2:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Fourteenth Dalai Lama
    ea4824eed3ca40d6aff836bae63e95c1:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Fourteenth Dalai Lama
    dad40c3bdaff41638fb46de76301f3e7:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    7014c97e60ae48fba59caac33899d7ad:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro
        Tsering Chödrön
      parent: Jamyang Khyentse Chökyi Lodrö
    29bfb822de2a4715bfd61468efe09891:
      title: 'Sweet Song of Enduring Deathlessness: A Prayer for the Long Life of
        Jamyang Khyentse Chökyi Lodrö'
      parent: Jamyang Khyentse Chökyi Lodrö
    e0b2881a2aee46c0b7793bcb8ec8a436:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      parent: Jetsün Lochen Incarnation
    e70cde130df943fd9ce3edd7bf387e3c:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      parent: Khandro Tāre Lhamo
    fc06a2788a97481296696e104df5ba7f:
      title: Prayer for the Long Life of Khandro Tsering Chödrön
      parent: Khandro Tsering Chödrön
    92969df181e64b939d245b4bf089bfcc:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Khyenrab Chökyi Özer
    aa9bab98f80f4891a37435e9b17f355a:
      title: 'The Flower of Auspiciousness: A Prayer for the Long Life of Khenpo Khyenrab
        Chökyi Özer, Masterful Expositor of Scripture and Reasoning'
      parent: Khyenrab Chökyi Özer
    a2330c761412475aa50a25726c174d12:
      title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long
        Life of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
      parent: Khyenrab Chökyi Özer
    84df85616d9b4f62946e6c2bb2da6e02:
      title: Prayer for the Long Life of Lochen Ngawang Chöpal
      parent: Lochen Dharmaśrī
    df2cc08f77724256b7bca08ba132b7b6:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Lodi Gyari Rinpoche
    9586077502e24d8483918506f11ae25a:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Mayum Tsering Wangmo
    c07dd2ce7efc4aa798b35fe397ed7de8:
      title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung
        Rinpoche'
      parent: Minling Chung Rinpoche
    e1af9821e25f4c97b8c5dd68d01a2ba6:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Namkhai Norbu Rinpoche
    e8b9d935b0724b9b9bbafdb6005505f8:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Neten Chokling Rinpoche
    e15e46e9fd3d4e5aa29d6715668c1efb:
      title: Prayer for the Long Life of Orgyen Tobgyal Rinpoche
      parent: Orgyen Tobgyal Rinpoche
    c5a7862a048948c9bf60581f161e04c6:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Patrick Gaffney
    a55d7d703bd54cd6bffe10498822d6c5:
      title: Prayer for the Long Life of Pema Norbu, Lord of Siddhas
      parent: Penor Rinpoche
    abbb33d74ca6488baa72c01c8023c235:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Pewar Rinpoche
    7db069a32303417ebb9b0fdb0aed4b5a:
      title: Prayer for the Long Life of the Glorious Sakyapa Father and Son
      parent: Sakya Dagchen and Son
    d367b19556554627aa9cea65b2c7c244:
      title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi
        Gyalpo, the Lord of Refuge and Precious Holder of the Throne of the Drolma
        Palace at Glorious Sakya
      parent: Sakya Trichen
    f5f14ece028d4d99b76fd156f599e241:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Sakya Trichen
    4d17b7442968405fbb10e35bcdcdd5a4:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Shechen Rabjam Rinpoche
    aece495f431c4c2caa78f9dc201bdfa1:
      title: The Excellent Stream of Nectar of Immortality
      parent: Sogyal Rinpoche
    e2590ff2fe6f4b4193c941b7c567f222:
      title: Gentle Rain of the Nectar of Immortality
      parent: Sogyal Rinpoche
    5b4dd1b1ea854b68ac79894880fa814e:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Sogyal Rinpoche
    c8a5103c6c2f4d2cb8621ff83eaef089:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Sogyal Rinpoche
    7ed7ae7b7c004b31b13cfb975c51652e:
      title: The Attainment of Immortality
      parent: Sogyal Rinpoche
    8c28c36b5b284ad2bcb50a1c714d8a0b:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Soktsé Rinpoche
    92d1b4b3f62d4da8a17385ac1bb3ec8d:
      title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in
        the Succession of Lotus-Tongued Jamchen Tai Situ Incarnations'
      parent: Tai Situ Rinpoche
    cf742df93eaf49c8b920b989e94a1906:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Taklung Tsetrul Rinpoche
    e6398321688d43de91d6ffdfa7ad1f00:
      title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the
        All-Knowing Paṇchen Rinpoche of Tsang'
      parent: Tenth Paṇchen Lama
    6c4d7f8374174a99b4ae13c92d365831:
      title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the
        Great Tertön and Vidyādhara Lerab Lingpa'
      parent: Tertön Sogyal Lerab Lingpa
    b08d065a5b394133a9d4b9af8155c12b:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Trulshik Rinpoche
    21e7c3ac134d4260a846afa4600d3877:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Trulshik Rinpoche
    0dec3b5778804fd0968eff213654acd7:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      parent: Tulku Thondup Rinpoche
created_at: '2022-03-01T04:19:58.003742'
last_modified_at: '2022-03-01T04:19:58.003745'
